name: Azure Static Website Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC login
  contents: read # Required to checkout repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Log in to Azure using OIDC
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # Service Principal Client ID
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} # Tenant ID
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      # 3️⃣ Verify login (optional)
      - name: Show Azure account
        run: az account show

      # 4️⃣ Run infrastructure setup script
      - name: Deploy Infrastructure & Website
        run: bash infra/infra.sh

      # 5️⃣ Verify VM and Public IP
      - name: Verify Deployment
        run: |
          echo "✅ Deployment complete."
          az vm list -d -o table
          az network public-ip show --resource-group rg-blizzy-static --name pip-blizzy -o table
