name: Azure Static Website Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
  AZ_LOCATION: uksouth
  RESOURCE_GROUP: rg-blizzy-static
  VNET_NAME: vnet-blizzy
  SUBNET_NAME: snet-web
  NSG_NAME: nsg-web
  VM_NAME: vm-blizzy-web
  PUBLIC_IP_NAME: pip-blizzy
  NIC_NAME: nic-blizzy
  VM_SIZE: Standard_B1s
  VM_IMAGE: UbuntuLTS
  ADMIN_USERNAME: azureuser
  SSH_KEY_PATH: ~/.ssh/id_rsa.pub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure login using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription context
        run: az account set --subscription $AZ_SUBSCRIPTION_ID

      - name: Run infrastructure setup
        run: bash infra/infra.sh

      - name: Verify deployment
        run: |
          echo "✅ Infrastructure deployed successfully"
          az vm list -o table
