name: Azure Static Website Deployment

on:
  push:
    branches:
      - main

env:
  AZURE_LOCATION: uksouth
  RESOURCE_GROUP: rg-blizzy-static
  VNET_NAME: vnet-blizzy
  SUBNET_NAME: snet-web
  NSG_NAME: nsg-web
  VM_NAME: vm-blizzy-web
  PUBLIC_IP_NAME: pip-blizzy
  NIC_NAME: nic-blizzy
  VM_SIZE: Standard_B1s
  AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription Context
        run: az account set --subscription $AZ_SUBSCRIPTION_ID

      - name: Run Infrastructure Setup
        run: bash infra/create_infra.sh

      - name: Verify Deployment
        run: |
          echo "✅ Infrastructure deployed successfully"
          az vm list -o table
