name: Azure Static Website Deployment

on:
  push:
    branches:
      - main

env:
  AZURE_LOCATION: uksouth
  RESOURCE_GROUP: rg-blizzy-static
  VNET_NAME: vnet-blizzy
  SUBNET_NAME: snet-web
  NSG_NAME: nsg-web
  VM_NAME: vm-blizzy-web
  PUBLIC_IP_NAME: pip-blizzy
  NIC_NAME: nic-blizzy
  VM_SIZE: Standard_B1s
  AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Login to Azure using service principal credentials
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true # optional, avoid PowerShell session if not needed

      # 3️⃣ Set subscription explicitly
      - name: Set Azure Subscription
        run: az account set --subscription $AZ_SUBSCRIPTION_ID

      # 4️⃣ Run infrastructure script
      - name: Deploy Infrastructure
        run: |
          chmod +x infra/infra.sh
          bash infra/infra.sh

      # 5️⃣ Verify deployment
      - name: Verify VM Deployment
        run: |
          VM_IP=$(az network public-ip show \
            --resource-group $RESOURCE_GROUP \
            --name $PUBLIC_IP_NAME \
            --query ipAddress -o tsv)
          echo "✅ Infrastructure deployed successfully."
          echo "VM Public IP: $VM_IP"
          echo "Website URL: http://$VM_IP/"
