name: Azure Static Website Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure login using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription context
        run: az account set --subscription ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Generate SSH Key for CI
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -q -N ""
          echo "SSH key generated for GitHub Actions CI."

      - name: Run infrastructure setup
        run: bash infra/infra.sh

      - name: Verify deployment
        run: |
          echo "✅ Infrastructure deployed successfully"
          az vm list -o table
